name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v2
      with:
        go-version: '>=1.22.0'

    - name: Build
      run: |
        go build

    - name: Test
      run: |
        go test -covermode=count -coverprofile=coverage.out

    - name: gosec
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec ./...

    - name: golangci-lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.59.1
        golangci-lint run --skip-files='.*_test.go'
